Added behavior to ignore matching directories
Adjective-Object/good-fences-rs-core pull request #17
Opened 2022-10-13 17:45 UTC by flickyiyo

2022-10-14 00:39 UTC, jarmit approved these changes

2022-10-17 16:13 UTC, Adjective-Object commented on src/good_fences_runner.rs
> +        ignored_dirs: Vec<String>,
`Option<Vec<String>>`

2022-10-17 19:27 UTC, Adjective-Object requested changes

2022-10-17 19:27 UTC, Adjective-Object commented on good-fences.js
> +     .option('--ignoredDirs [paths...]', 'Excludes matching dirs from fence evaluation (e.g. `--ignoreDirs lib` will not evaluate source files in all dirs named `lib`', [])
If this epects regexes, the documentation should cover that this expects regexes

2022-10-17 19:27 UTC, Adjective-Object commented on src/evaluate_fences.rs
> +    ignored_dirs: Vec<String>,
Option<Vec<String>>, this is an optional parameter. You can just `unwrap_or` and default to an empty vec.

2022-10-17 19:27 UTC, Adjective-Object commented on src/evaluate_fences.rs
> +            .expect("unable to match --ignoredDirs")
this error message should include the regexp that failed to compile

2022-10-17 19:27 UTC, Adjective-Object commented on src/evaluate_fences.rs
> +            .expect("unable to match --ignoredDirs")
This recompiles the regexp on every single fence. That is needlessly wasteful.

The regexps should be compiled once, and used to filter out ignored fences during walk_dirs.

2022-10-18 19:36 UTC, merged