Added readme info and modified good-fences default value
Adjective-Object/good-fences-rs-core pull request #22
Opened 2022-10-18 23:04 UTC by flickyiyo

2022-10-20 13:09 UTC, Adjective-Object requested changes
Typos and rephrasing. Sorry for all the nitpicking.

2022-10-20 22:12 UTC, jarmit approved these changes

2022-10-21 20:22 UTC, flickyiyo commented on README.md
> +- `GCLIB` >= 2.27 (preinstalled with ubuntu 18)
Seems to not be the case anymore, in any case let me first verify that.

2022-10-27 20:08 UTC, flickyiyo commented on README.md
> +If you have your tsconfig file splitted and want to use the one containing `compilerOptions.paths` instead of the default `tsconfig.json`
Sorry for my non-native language writing skills.

2022-10-28 16:06 UTC, Adjective-Object approved these changes

2022-10-28 20:02 UTC, merged