Fix tests, relative paths, slashed paths, other stuff
Adjective-Object/good-fences-rs-core pull request #7
Opened 2022-09-09 20:18 UTC by flickyiyo

2022-09-09 22:30 UTC, Adjective-Object requested changes
nits and cleanliness

2022-09-09 22:30 UTC, Adjective-Object commented on src/fence_collection.rs
> +                "some/fucking/fence.json" =>  parse_fence_str(r#"{"tags": ["fucking"]}"#, &RelativePathBuf::from("path/to/protected/fence.json")).unwrap()
```suggestion
                "some/other/fence.json" =>  parse_fence_str(r#"{"tags": ["other"]}"#, &RelativePathBuf::from("path/to/protected/fence.json")).unwrap()
```

2022-09-09 22:30 UTC, Adjective-Object commented on src/fence_collection.rs
> +    }
```suggestion
        assert_eq!(
            fence_collection.get_fences_for_path(&Path::new("some/other/file.ts")),
            vec![
                fence_collection.fences_map.get("some/other/fence.json").unwrap(),
                fence_collection.fences_map.get("some/fence.json").unwrap(),
            ],
            "should return multiple fences for file with multiple fences",
        );
    }
```

2022-09-09 22:30 UTC, Adjective-Object commented on src/get_imports/import_path_visitor.rs
> +        // export.
```suggestion
```

2022-09-09 22:30 UTC, Adjective-Object commented on src/get_imports/import_path_visitor.rs
> +        // println!("{:?}", module.body);
```suggestion
```

2022-09-12 13:03 UTC, flickyiyo commented on src/fence_collection.rs
> +    }
boo!

![mood-boo](https://user-images.githubusercontent.com/26918372/189660487-d923bbf4-3483-4042-a616-5f66e938932d.gif)

2022-09-12 17:53 UTC, merged